version = 0.1
[default.deploy.parameters]
stack_name = "todo-app"
resolve_s3 = true
s3_prefix = "todo-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Table=\"Actions\" Region=\"eu-west-1\" AWSenv=\"AWS\" UserPoolId=\"\" AppClientId=\"\""
image_repositories = []
